/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Person(props: any) {
  const { nodes, materials } = useGLTF('../model/futurista.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Mesh_0"
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0.geometry}
        material={materials.Material_0}
        position={[0, -0.15, 2.5]}
      />
    </group>
  )
}

useGLTF.preload('/futurista.glb')
