/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Man(props:any) {
  const { nodes, materials } = useGLTF('../model/silverman2.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Mesh1"
        castShadow
        receiveShadow
        geometry={nodes.Mesh1.geometry}
        material={materials['Scratched metal']}
        position={[0, -0.15, 2.5]}
      >
        <meshStandardMaterial
          color={0xaaaaaa}    // Base color similar al cromo
          metalness={1}       // Material totalmente metálico
          roughness={0.2}     // Superficie brillante
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('../model/silverman2.glb')
